export const TEST_PRODUCTS = [
  {
    id: 1111,
    ownerId: "10",
    title: "Test product 1",
    description:
      "Test product description Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the",
    photos: [
      "file:///data/user/0/host.exp.exponent/cache/ExperienceData/%2540anonymous%252Fexpoproject-aeb8be29-bf3a-4275-a960-54282c5f6b7a/ImagePicker/c3dbdf38-2c1f-463f-ba1e-97ca1d9188de.jpeg",
    ],
    location: "Lviv",
    price: 332,
    saved: false,
    createdAt: `${Date.now()}`,
    updatedAt: `${Date.now()}`,
    owner: {
      email: "testuser@gamil.com",
      fullName: "Test User",
      id: "10",
      location: "Ternopil",
      avatar:
        "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png",
      phone: "sdfdfdfdsf",
      createdAt: "dfsf",
      updatedAt: "gksfngkf",
    },
  },
  {
    id: Date.now() + 1,
    ownerId: "10",
    title: "Test product 2",
    description:
      "Test product description Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the",
    photos: [
      "file:///data/user/0/host.exp.exponent/cache/ExperienceData/%2540anonymous%252Fexpoproject-aeb8be29-bf3a-4275-a960-54282c5f6b7a/ImagePicker/c3dbdf38-2c1f-463f-ba1e-97ca1d9188de.jpeg",
    ],
    location: "Ivano-Fran.",
    price: 332,
    saved: false,
    createdAt: `${Date.now()}`,
    updatedAt: `${Date.now()}`,
    owner: {
      email: "testuser@gamil.com",
      fullName: "Test User",
      id: "10",
      location: "fdsf",
      avatar:
        "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png",
      phone: "sdfdfdfdsf",
      createdAt: "dfsf",
      updatedAt: "gksfngkf",
    },
  },
  {
    id: Date.now() + 2,
    ownerId: "10",
    title: "Test product 3",
    description: "Test product description",
    photos: [
      "file:///data/user/0/host.exp.exponent/cache/ExperienceData/%2540anonymous%252Fexpoproject-aeb8be29-bf3a-4275-a960-54282c5f6b7a/ImagePicker/c3dbdf38-2c1f-463f-ba1e-97ca1d9188de.jpeg",
    ],
    location: "Ternopil",
    price: 332,
    saved: false,
    createdAt: `${Date.now()}`,
    updatedAt: `${Date.now()}`,
    owner: {
      email: "testuser@gamil.com",
      fullName: "Test User",
      id: "10",
      location: "fdsf",
      avatar:
        "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png",
      phone: "sdfdfdfdsf",
      createdAt: "dfsf",
      updatedAt: "gksfngkf",
    },
  },
  {
    id: Date.now() + 3,
    ownerId: "10",
    title: "Test product 4",
    description: "Test product description",
    photos: [
      "file:///data/user/0/host.exp.exponent/cache/ExperienceData/%2540anonymous%252Fexpoproject-aeb8be29-bf3a-4275-a960-54282c5f6b7a/ImagePicker/c3dbdf38-2c1f-463f-ba1e-97ca1d9188de.jpeg",
    ],
    location: "ladssd",
    price: 332,
    saved: false,
    createdAt: `${Date.now()}`,
    updatedAt: `${Date.now()}`,
    owner: {
      email: "testuser@gamil.com",
      fullName: "Test User",
      id: "10",
      location: "fdsf",
      avatar:
        "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png",
      phone: "sdfdfdfdsf",
      createdAt: "dfsf",
      updatedAt: "gksfngkf",
    },
  },
  {
    id: Date.now() + 4,
    ownerId: "10",
    title: "Test product",
    description: "Test product description",
    photos: [
      "file:///data/user/0/host.exp.exponent/cache/ExperienceData/%2540anonymous%252Fexpoproject-aeb8be29-bf3a-4275-a960-54282c5f6b7a/ImagePicker/c3dbdf38-2c1f-463f-ba1e-97ca1d9188de.jpeg",
    ],
    location: "ladssd",
    price: 332,
    saved: false,
    createdAt: `${Date.now()}`,
    updatedAt: `${Date.now()}`,
    owner: {
      email: "testuser@gamil.com",
      fullName: "Test User",
      id: "10",
      location: "fdsf",
      avatar:
        "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png",
      phone: "sdfdfdfdsf",
      createdAt: "dfsf",
      updatedAt: "gksfngkf",
    },
  },
  {
    id: Date.now() + 5,
    ownerId: "10",
    title: "Test product",
    description: "Test product description",
    photos: [
      "file:///data/user/0/host.exp.exponent/cache/ExperienceData/%2540anonymous%252Fexpoproject-aeb8be29-bf3a-4275-a960-54282c5f6b7a/ImagePicker/c3dbdf38-2c1f-463f-ba1e-97ca1d9188de.jpeg",
    ],
    location: "ladssd",
    price: 332,
    saved: false,
    createdAt: `${Date.now()}`,
    updatedAt: `${Date.now()}`,
    owner: {
      email: "testuser@gamil.com",
      fullName: "Test User",
      id: "10",
      location: "fdsf",
      avatar:
        "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png",
      phone: "sdfdfdfdsf",
      createdAt: "dfsf",
      updatedAt: "gksfngkf",
    },
  },
  {
    id: Date.now() + 6,
    ownerId: "10",
    title: "Test product",
    description: "Test product description",
    photos: [
      "file:///data/user/0/host.exp.exponent/cache/ExperienceData/%2540anonymous%252Fexpoproject-aeb8be29-bf3a-4275-a960-54282c5f6b7a/ImagePicker/c3dbdf38-2c1f-463f-ba1e-97ca1d9188de.jpeg",
    ],
    location: "ladssd",
    price: 332,
    saved: false,
    createdAt: `${Date.now()}`,
    updatedAt: `${Date.now()}`,
    owner: {
      email: "testuser@gamil.com",
      fullName: "Test User",
      id: "10",
      location: "fdsf",
      avatar:
        "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png",
      phone: "sdfdfdfdsf",
      createdAt: "dfsf",
      updatedAt: "gksfngkf",
    },
  },
  {
    id: Date.now() + 7,
    ownerId: "10",
    title: "Test product",
    description: "Test product description",
    photos: [
      "file:///data/user/0/host.exp.exponent/cache/ExperienceData/%2540anonymous%252Fexpoproject-aeb8be29-bf3a-4275-a960-54282c5f6b7a/ImagePicker/c3dbdf38-2c1f-463f-ba1e-97ca1d9188de.jpeg",
    ],
    location: "ladssd",
    price: 332,
    saved: false,
    createdAt: `${Date.now()}`,
    updatedAt: `${Date.now()}`,
    owner: {
      email: "testuser@gamil.com",
      fullName: "Test User",
      id: "10",
      location: "fdsf",
      avatar:
        "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png",
      phone: "sdfdfdfdsf",
      createdAt: "dfsf",
      updatedAt: "gksfngkf",
    },
  },
  {
    id: Date.now() + 8,
    ownerId: "10",
    title: "Test product",
    description: "Test product description",
    photos: [
      "file:///data/user/0/host.exp.exponent/cache/ExperienceData/%2540anonymous%252Fexpoproject-aeb8be29-bf3a-4275-a960-54282c5f6b7a/ImagePicker/c3dbdf38-2c1f-463f-ba1e-97ca1d9188de.jpeg",
    ],
    location: "ladssd",
    price: 332,
    saved: false,
    createdAt: `${Date.now()}`,
    updatedAt: `${Date.now()}`,
    owner: {
      email: "testuser@gamil.com",
      fullName: "Test User",
      id: "10",
      location: "fdsf",
      avatar:
        "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png",
      phone: "sdfdfdfdsf",
      createdAt: "dfsf",
      updatedAt: "gksfngkf",
    },
  },
  {
    id: Date.now() + 9,
    ownerId: "10",
    title: "Test product",
    description: "Test product description",
    photos: [
      "file:///data/user/0/host.exp.exponent/cache/ExperienceData/%2540anonymous%252Fexpoproject-aeb8be29-bf3a-4275-a960-54282c5f6b7a/ImagePicker/c3dbdf38-2c1f-463f-ba1e-97ca1d9188de.jpeg",
    ],
    location: "ladssd",
    price: 332,
    saved: false,
    createdAt: `${Date.now()}`,
    updatedAt: `${Date.now()}`,
    owner: {
      email: "testuser@gamil.com",
      fullName: "Test User",
      id: "10",
      location: "fdsf",
      avatar:
        "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png",
      phone: "sdfdfdfdsf",
      createdAt: "dfsf",
      updatedAt: "gksfngkf",
    },
  },
  {
    id: Date.now() + 10,
    ownerId: "10",
    title: "Test product",
    description: "Test product description",
    photos: [
      "file:///data/user/0/host.exp.exponent/cache/ExperienceData/%2540anonymous%252Fexpoproject-aeb8be29-bf3a-4275-a960-54282c5f6b7a/ImagePicker/c3dbdf38-2c1f-463f-ba1e-97ca1d9188de.jpeg",
    ],
    location: "ladssd",
    price: 332,
    saved: false,
    createdAt: `${Date.now()}`,
    updatedAt: `${Date.now()}`,
    owner: {
      email: "testuser@gamil.com",
      fullName: "Test User",
      id: "10",
      location: "fdsf",
      avatar:
        "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png",
      phone: "sdfdfdfdsf",
      createdAt: "dfsf",
      updatedAt: "gksfngkf",
    },
  },
];

export function createNewProduct(body) {
  const newProduct = {
    id: Date.now(),
    ownerId: "10",
    title: body.title,
    description: body.description,
    photos: body.images,
    location: body.location,
    price: +body.price,
    saved: false,
    createdAt: `${Date.now()}`,
    updatedAt: `${Date.now()}`,
    owner: {
      email: "testuser@gamil.com",
      fullName: "Test User",
      id: "10",
      location: "fdsf",
      avatar:
        "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png",
      phone: "sdfdfdfdsf",
      createdAt: "dfsf",
      updatedAt: "gksfngkf",
    },
  };
  TEST_PRODUCTS.push(newProduct);
  return {
    data: newProduct,
  };
}

export const CHATS = [
  {
    id: 387,
    productId: 33,
    ownerId: "10",
    createdAt: 22,
    updatedAt: 22,

    message: {
      id: 3384,
      chatId: 22,
      ownerId: "10",
      text: "Hey, how are you, friend?",
      read: false,
      createdAt: 3232,
      updatedAt: 321321,
    },
    product: {
      id: 2368,
      ownerId: "10",
      title: "masdmsa",
      description: "body.description",
      photos: ["body.images"],
      location: "body.location",
      price: 44,
      saved: false,
      createdAt: `${Date.now()}`,
      updatedAt: `${Date.now()}`,
      owner: {
        email: "testuser@gamil.com",
        fullName: "Test User",
        id: "10",
        location: "fdsf",
        avatar:
          "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png",
        phone: "sdfdfdfdsf",
        createdAt: "dfsf",
        updatedAt: "gksfngkf",
      },
    },

    participants: [
      {
        id: "10",
        email: "testuser@gamil.com",
        fullName: "Test User",
        location: "fdsf",
        avatar:
          "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png",
        phone: "sdfdfdfdsf",
        createdAt: "dfsf",
        updatedAt: "gksfngkf",
        ownProducts: {
          items: [
            {
              id: "ASDSM",
              ownerId: "10",
              title: "masdmsa",
              description: "body.description",
              photos: ["body.images"],
              location: "body.location",
              price: 44,
              saved: false,
              createdAt: `${Date.now()}`,
              updatedAt: `${Date.now()}`,
              owner: {
                email: "testuser@gamil.com",
                fullName: "Test User",
                id: "10",
                location: "fdsf",
                avatar:
                  "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png",
                phone: "sdfdfdfdsf",
                createdAt: "dfsf",
                updatedAt: "gksfngkf",
              },
            },
          ],
          searchItems: [],
        },
      },
      {
        id: "20",
        email: "testuser@gamil.com",
        fullName: "Test User",
        location: "fdsf",
        avatar:
          "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png",
        phone: "sdfdfdfdsf",
        createdAt: "dfsf",
        updatedAt: "gksfngkf",
        ownProducts: [
          {
            id: "ASDSM",
            ownerId: "20",
            title: "masdmsa",
            description: "body.description",
            photos: ["body.images"],
            location: "body.location",
            price: 44,
            saved: false,
            createdAt: `${Date.now()}`,
            updatedAt: `${Date.now()}`,
            owner: {
              email: "testuser@gamil.com",
              fullName: "Test User",
              id: "20",
              location: "fdsf",
              avatar:
                "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png",
              phone: "sdfdfdfdsf",
              createdAt: "dfsf",
              updatedAt: "gksfngkf",
            },
          },
        ],
      },
    ],
  },
  // chat 2
  {
    id: 307,
    productId: 33,
    ownerId: "20",
    createdAt: 22,
    updatedAt: 22,
    messages: {},
    message: {
      id: 3385,
      chatId: 22,
      ownerId: "20",
      text: "dlsamdsd",
      read: true,
      createdAt: 3232,
      updatedAt: 321321,
    },
    product: {
      id: 2367,
      ownerId: "20",
      title: "masdmsa",
      description: "body.description",
      photos: ["body.images"],
      location: "body.location",
      price: 44,
      saved: false,
      createdAt: `${Date.now()}`,
      updatedAt: `${Date.now()}`,
      owner: {
        email: "testuser@gamil.com",
        fullName: "Test User",
        id: "20",
        location: "fdsf",
        avatar:
          "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png",
        phone: "sdfdfdfdsf",
        createdAt: "dfsf",
        updatedAt: "gksfngkf",
      },
    },

    participants: [
      {
        id: "10",
        email: "testuser@gamil.com",
        fullName: "Test User",
        location: "fdsf",
        avatar:
          "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png",
        phone: "sdfdfdfdsf",
        createdAt: "dfsf",
        updatedAt: "gksfngkf",
        ownProducts: [
          {
            id: "ASDSM",
            ownerId: "10",
            title: "masdmsa",
            description: "body.description",
            photos: ["body.images"],
            location: "body.location",
            price: 44,
            saved: false,
            createdAt: `${Date.now()}`,
            updatedAt: `${Date.now()}`,
            owner: {
              email: "testuser@gamil.com",
              fullName: "Test User",
              id: "10",
              location: "fdsf",
              avatar:
                "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png",
              phone: "sdfdfdfdsf",
              createdAt: "dfsf",
              updatedAt: "gksfngkf",
            },
          },
        ],
      },
      {
        id: "10",
        email: "testuser@gamil.com",
        fullName: "Test User",
        location: "fdsf",
        avatar:
          "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png",
        phone: "sdfdfdfdsf",
        createdAt: "dfsf",
        updatedAt: "gksfngkf",
        ownProducts: [
          {
            id: "ASDSM",
            ownerId: "10",
            title: "masdmsa",
            description: "body.description",
            photos: ["body.images"],
            location: "body.location",
            price: 44,
            saved: false,
            createdAt: `${Date.now()}`,
            updatedAt: `${Date.now()}`,
            owner: {
              email: "testuser@gamil.com",
              fullName: "Test User",
              id: "10",
              location: "fdsf",
              avatar:
                "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png",
              phone: "sdfdfdfdsf",
              createdAt: "dfsf",
              updatedAt: "gksfngkf",
            },
          },
        ],
      },
    ],
  },
];

export const MESSAGES = [
  {
    id: 3386,
    chatId: 22,
    ownerId: "20",
    text: "Hello",
    read: true,
    createdAt: 3232,
    updatedAt: 321321,
  },
  {
    id: 3387,
    chatId: 22,
    ownerId: "10",
    text: "Hello",
    read: true,
    createdAt: 3232,
    updatedAt: 321321,
  },
  {
    id: 3388,
    chatId: 22,
    ownerId: "20",
    text: "How are you?",
    read: true,
    createdAt: 3232,
    updatedAt: 321321,
  },
  {
    id: 3389,
    chatId: 22,
    ownerId: "10",
    text: "Hello",
    read: true,
    createdAt: 3232,
    updatedAt: 321321,
  },
  {
    id: 3390,
    chatId: 22,
    ownerId: "20",
    text: "Hello",
    read: true,
    createdAt: 3232,
    updatedAt: 321321,
  },
];
